# Generated by Django 3.2.4 on 2021-06-26 22:36

import ajira.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ajira.models.UserCustomManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='leave',
            name='department',
        ),
    ]
