# Generated by Django 3.2.4 on 2021-06-24 09:20

import ajira.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ajira.models.UserCustomManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Human Resource', 'Human Resource'), ('Marketing', 'Marketing'), ('Accounting', 'Accounting')], default='Marketing', max_length=20),
        ),
    ]
