# Generated by Django 3.2.4 on 2021-06-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Human Resource', 'Human Resource'), ('Marketing', 'Marketing'), ('Accounting', 'Accounting')], default='Marketing', max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'december')], max_length=10)),
                ('year', models.IntegerField(max_length=4)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(max_length=200)),
            ],
        ),
    ]
