# Generated by Django 3.2.4 on 2021-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='year',
            field=models.IntegerField(),
        ),
    ]
