# Generated by Django 3.2.4 on 2021-06-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0003_alter_employeesalary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
    ]
