# Generated by Django 3.2.4 on 2021-06-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0004_alter_employeesalary_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
    ]
